/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-36-g20c8a3f5ff-20241122"
#endif /* AVUTIL_FFVERSION_H */
