/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114280-g0b7d4fccce-20240320"
#endif /* AVUTIL_FFVERSION_H */
